/*
 * Copyright (C) 2025-2026 Exeris Systems.
 * SPDX-License-Identifier: Apache-2.0
 */
package eu.exeris.kernel.spi.websocket;

import java.util.Optional;

/**
 * Kernel-scoped WebSocket bindings, for the deployment that boots the kernel.
 *
 * <h2>Why this exists alongside the direct path</h2>
 * <p>ADR-084 §1 decided that a provider yields an engine <em>without</em> booting the kernel, because
 * an LSP server starting per session must not pay for a runtime it does not use. That decision is
 * unchanged and these slots do not touch it: {@code WebSocketProvider.createServerEngine} still works
 * with nothing bound.
 *
 * <p>What the decision did not settle is the other deployment. An application that <em>does</em> boot
 * the kernel — written by hand or generated by the tooling — had no way to reach a WebSocket endpoint
 * except by naming a Community provider class itself, which puts a driver on its compile classpath and
 * is the coupling the Wall exists to prevent. Both shapes are legitimate; only one of them had a path.
 *
 * <h2>What binds these</h2>
 * <p>The {@code websocket} subsystem, and only when configuration enables it. A kernel booted without
 * {@code websocket.enabled=true} binds nothing here and opens no listener — adding the subsystem must
 * not give every existing deployment a socket it did not ask for.
 *
 * <p>Deliberately the same shape as {@code HttpKernelProviders}: an application supplies its handler
 * through {@link #WEBSOCKET_SERVER_HANDLER} before boot, and reads the running engine back out of
 * {@link #WEBSOCKET_SERVER_ENGINE}.
 *
 * @since 0.12
 */
public final class WebSocketKernelProviders {

    /** The provider the subsystem selected, by highest {@code priority()}. */
    public static final ScopedValue<WebSocketProvider> WEBSOCKET_PROVIDER = ScopedValue.newInstance();

    /** The engine the subsystem booted; bound only when the subsystem is enabled and started. */
    public static final ScopedValue<WebSocketServerEngine> WEBSOCKET_SERVER_ENGINE =
            ScopedValue.newInstance();

    /**
     * The application's message handler, supplied <em>into</em> the boot.
     *
     * <p>Unbound is not an error: a kernel with the subsystem enabled and no handler serves a socket
     * that accepts and drains, which is what makes the subsystem safe to enable before an application
     * has one. It is the WebSocket mirror of {@code HTTP_SERVER_HANDLER}.
     */
    public static final ScopedValue<WebSocketHandler> WEBSOCKET_SERVER_HANDLER =
            ScopedValue.newInstance();

    /**
     * The application's handshake policy, supplied into the boot.
     *
     * <p>Unbound leaves the engine's default, which ADR-084 §6 specifies as refusing by default —
     * so an unconfigured deployment refuses upgrades rather than accepting them.
     */
    public static final ScopedValue<WebSocketHandshakeHandler> WEBSOCKET_HANDSHAKE_HANDLER =
            ScopedValue.newInstance();

    private WebSocketKernelProviders() {
    }

    /**
     * The booted engine, if the subsystem is enabled and running.
     *
     * @return the engine, or empty when the subsystem is disabled or has not started
     */
    public static Optional<WebSocketServerEngine> webSocketServerEngine() {
        return WEBSOCKET_SERVER_ENGINE.isBound()
                ? Optional.of(WEBSOCKET_SERVER_ENGINE.get())
                : Optional.empty();
    }

    /**
     * The application's handler, if it supplied one.
     *
     * @return the handler, or empty when none was bound
     */
    public static Optional<WebSocketHandler> webSocketServerHandler() {
        return WEBSOCKET_SERVER_HANDLER.isBound()
                ? Optional.of(WEBSOCKET_SERVER_HANDLER.get())
                : Optional.empty();
    }

    /**
     * The application's handshake policy, if it supplied one.
     *
     * @return the handshake handler, or empty when none was bound
     */
    public static Optional<WebSocketHandshakeHandler> webSocketHandshakeHandler() {
        return WEBSOCKET_HANDSHAKE_HANDLER.isBound()
                ? Optional.of(WEBSOCKET_HANDSHAKE_HANDLER.get())
                : Optional.empty();
    }
}
