sonar.projectKey=exeris-systems_exeris-kernel
sonar.projectName=Exeris Kernel
sonar.projectVersion=0.6.0

sonar.sourceEncoding=UTF-8
sonar.java.source=26
sonar.newCode.referenceBranch=main

sonar.sources=exeris-kernel-spi/src/main,exeris-kernel-core/src/main,exeris-kernel-community/src/main,exeris-kernel-community-testkit/src/main,exeris-kernel-tck/src/main,tools/jfr-reporter/src/main
sonar.tests=exeris-kernel-spi/src/test,exeris-kernel-core/src/test,exeris-kernel-community/src/test,exeris-kernel-tck/src/test

sonar.exclusions=**/target/**,**/.idea/**,**/kernel-legacy/**,**/native-libs/**,**/*.md
sonar.coverage.exclusions=**/*Benchmark*.java,**/target/**
sonar.cpd.exclusions=**/*Benchmark*.java
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
