/*
 * Copyright (C) 2025-2026 Exeris Systems.
 * SPDX-License-Identifier: Apache-2.0
 */
package eu.exeris.kernel.community.bootstrap;

import eu.exeris.kernel.spi.bootstrap.BootstrapPhase;
import eu.exeris.kernel.spi.bootstrap.Subsystem;
import eu.exeris.kernel.spi.config.ConfigProvider;
import eu.exeris.kernel.spi.context.KernelProviders;
import eu.exeris.kernel.spi.websocket.WebSocketConfig;
import eu.exeris.kernel.spi.websocket.WebSocketKernelProviders;
import eu.exeris.kernel.spi.websocket.WebSocketProvider;
import eu.exeris.kernel.spi.websocket.WebSocketServerEngine;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.ServiceLoader;
import java.util.function.UnaryOperator;

/**
 * Boots a WebSocket endpoint for the application that boots the kernel.
 *
 * <h2>The other half of ADR-084 §1</h2>
 * <p>That section decides a provider yields an engine <em>without</em> booting the kernel, because a
 * per-session LSP server must not pay for a runtime it does not use. It remains true and this
 * subsystem does not touch it — {@code WebSocketProvider.createServerEngine} still works with nothing
 * bound.
 *
 * <p>What it did not decide is that the no-boot path is the <em>only</em> path. An application that
 * does boot the kernel, hand-written or generated by the tooling, could reach an endpoint only by
 * naming a Community provider class itself: a driver on its compile classpath, which is the coupling
 * the Wall exists to prevent. Both deployments are legitimate; one of them had no path.
 *
 * <h2>Inert unless configured</h2>
 * <p>{@code websocket.enabled} defaults to {@code false}, so a kernel that upgrades to this version
 * binds nothing here and opens no listener. That is not caution for its own sake: a listener appearing
 * because a dependency was bumped is a security regression shipped as a feature.
 *
 * <p>Deliberately the same shape as {@link CommunityHttpSubsystem}, including handler resolution — the
 * application supplies {@code WEBSOCKET_SERVER_HANDLER} into the boot, and a subsystem enabled without
 * one serves a socket that accepts and drains rather than refusing to start.
 */
final class CommunityWebSocketSubsystem implements Subsystem {

    private WebSocketProvider provider;
    private WebSocketServerEngine serverEngine;
    private boolean running;

    @Override
    public String name() {
        return "websocket";
    }

    @Override
    public List<String> dependsOn() {
        // Orders the phases; it does NOT make MEMORY_ALLOCATOR visible during initialize(), because
        // providerBindings() composition runs after every subsystem has initialised. The engine is
        // therefore built at start() — see DeferredWebSocketServerEngine — so that inside a boot it
        // shares the allocator the memory subsystem owns instead of opening a second budget beside it.
        return List.of("memory");
    }

    @Override
    public BootstrapPhase phase() {
        return BootstrapPhase.RUNTIME;
    }

    @Override
    public void initialize() {
        ConfigProvider configProvider = KernelProviders.CURRENT_CONFIG.get();
        if (!CommunityWebSocketConfigResolver.isEnabled(configProvider)) {
            return;
        }
        WebSocketConfig config = CommunityWebSocketConfigResolver.buildWebSocketConfig(configProvider);
        provider = ServiceLoader.load(WebSocketProvider.class)
                .stream()
                .map(ServiceLoader.Provider::get)
                .max(Comparator.comparingInt(WebSocketProvider::priority))
                .orElseThrow(() -> new IllegalStateException(
                        "websocket.enabled is true but no WebSocketProvider is on the classpath"));
        // Deferred: the allocator is not bound yet — see DeferredWebSocketServerEngine.
        serverEngine = new DeferredWebSocketServerEngine(provider, config);
    }

    @Override
    public void start() {
        if (serverEngine == null) {
            return;
        }
        WebSocketKernelProviders.webSocketServerHandler()
                .ifPresentOrElse(serverEngine::setHandler,
                        () -> serverEngine.setHandler(CommunityWebSocketSubsystem::drain));
        WebSocketKernelProviders.webSocketHandshakeHandler()
                .ifPresent(serverEngine::setHandshakeHandler);
        serverEngine.start();
        running = true;
    }

    /**
     * Accepts and discards. A subsystem enabled before the application has a handler must not refuse
     * to boot, and must not leave frames unread either.
     */
    private static void drain(eu.exeris.kernel.spi.websocket.WebSocketExchange exchange) {
        String message = exchange.receive();
        while (message != null) {
            message = exchange.receive();
        }
    }

    @Override
    public void stop() {
        running = false;
        if (serverEngine != null) {
            serverEngine.close();
        }
    }

    @Override
    public boolean isRunning() {
        return running;
    }

    @Override
    public UnaryOperator<ScopedValue.Carrier> providerBindings() {
        if (provider == null) {
            return Subsystem.super.providerBindings();
        }
        List<CommunityCarrierBindings.Binding<?>> bindings = new ArrayList<>(2);
        bindings.add(CommunityCarrierBindings.binding(
                WebSocketKernelProviders.WEBSOCKET_PROVIDER, provider));
        if (serverEngine != null) {
            bindings.add(CommunityCarrierBindings.binding(
                    WebSocketKernelProviders.WEBSOCKET_SERVER_ENGINE, serverEngine));
        }
        return CommunityCarrierBindings.operator(bindings);
    }
}
