/*
 * Copyright (C) 2025-2026 Exeris Systems.
 *
 * Licensed under the Apache License, Version 2.0 with Commons Clause.
 * You may use, modify, and distribute this file under those terms.
 * Commercial resale of this software as a competing product is prohibited.
 * See LICENSE-COMMUNITY in the repository root for the full text.
 */
package eu.exeris.kernel.community.persistence;

import eu.exeris.kernel.community.persistence.jdbc.CommunityJdbcEventStore;
import eu.exeris.kernel.spi.persistence.EventStore;
import eu.exeris.kernel.spi.persistence.PersistenceConfig;
import eu.exeris.kernel.spi.persistence.PersistenceConnection;
import eu.exeris.kernel.spi.persistence.PersistenceEngine;
import eu.exeris.kernel.tck.contract.persistence.AbstractEventStoreTck;
import org.junit.jupiter.api.DisplayName;

import java.util.Map;

/**
 * Community binding of {@link AbstractEventStoreTck}.
 *
 * <p>Uses H2 in PostgreSQL mode to validate the SPI outbox contract:
 * append/poll/mark + transactional visibility semantics.
 */
@DisplayName("Community: EventStore TCK")
class CommunityEventStoreTckTest extends AbstractEventStoreTck {

    @Override
    protected PersistenceEngine createEngine() {
        PersistenceEngine engine = new CommunityPersistenceProvider().createEngine(testConfig());
        initializeOutboxSchema(engine);
        return engine;
    }

    @Override
    protected EventStore createEventStore(PersistenceConnection connection) {
        return new CommunityJdbcEventStore(connection);
    }

    private static void initializeOutboxSchema(PersistenceEngine engine) {
        try (PersistenceConnection connection = engine.openConnection()) {
            connection.beginTransaction();
            connection.executeUpdate(
                    "CREATE TABLE IF NOT EXISTS exeris_outbox (" +
                        "outbox_seq BIGINT GENERATED BY DEFAULT AS IDENTITY, " +
                            "id UUID PRIMARY KEY, " +
                            "aggregate_id VARCHAR(255) NOT NULL, " +
                            "aggregate_type VARCHAR(255) NOT NULL, " +
                            "event_type VARCHAR(255) NOT NULL, " +
                        "payload BYTEA NOT NULL, " +
                            "occurred_at BIGINT NOT NULL, " +
                            "published_at BIGINT, " +
                            "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP" +
                            ")");
            connection.executeUpdate(
                            "CREATE UNIQUE INDEX IF NOT EXISTS idx_exeris_outbox_seq " +
                                "ON exeris_outbox (outbox_seq)");
                        connection.executeUpdate(
                    "CREATE INDEX IF NOT EXISTS idx_exeris_outbox_unpublished " +
                                "ON exeris_outbox (published_at, outbox_seq)");
            connection.commit();
        }
    }

    private static PersistenceConfig testConfig() {
        return new PersistenceConfig(
                "jdbc:h2:mem:community_eventstore_tck_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "",
                16,
                4,
                5_000L,
                60_000L,
                600_000L,
                false,
                false,
                false,
                0,
                Map.of()
        );
    }
}
