/*
 * Copyright (C) 2025-2026 Exeris Systems.
 *
 * Licensed under the Apache License, Version 2.0 with Commons Clause.
 * You may use, modify, and distribute this file under those terms.
 * Commercial resale of this software as a competing product is prohibited.
 * See LICENSE-COMMUNITY in the repository root for the full text.
 */
package eu.exeris.kernel.core.crypto.tls;

import eu.exeris.kernel.core.crypto.ArenaLoanedBuffer;
import eu.exeris.kernel.core.crypto.openssl.CoreOpenSslLoader;
import eu.exeris.kernel.core.crypto.openssl.CoreSslHandles;
import eu.exeris.kernel.spi.context.KernelProviders;
import eu.exeris.kernel.spi.crypto.TlsPhase;
import eu.exeris.kernel.spi.crypto.TlsStatus;
import eu.exeris.kernel.spi.memory.AllocationHint;
import eu.exeris.kernel.spi.memory.LoanedBuffer;
import eu.exeris.kernel.spi.memory.MemoryAllocator;
import eu.exeris.kernel.spi.memory.MemoryStats;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledOnOs;
import org.junit.jupiter.api.condition.OS;
import org.junit.jupiter.api.io.TempDir;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.net.InetSocketAddress;
import java.nio.channels.ServerSocketChannel;
import java.nio.channels.SocketChannel;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * Integration Test: Full TLS 1.3 handshake + round-trip data transfer over a real
 * loopback TCP socket using {@link OffHeapTlsEngine}.
 *
 * <h2>Why this test exists</h2>
 * <p>Per {@code docs/subsystems/crypto.md} Testing Strategy: "Unit Tests: CommunityTlsEngine
 * handshake over loopback — no io_uring, no QUIC, pure TCP." This test validates that
 * the engine correctly drives {@code SSL_accept}/{@code SSL_connect} over real kernel
 * file descriptors to completion, satisfying TRL-4 readiness.
 *
 * <h2>Scope</h2>
 * <ul>
 *   <li>Server: {@code SSL_CTX} with self-signed cert/key generated by OpenSSL CLI.</li>
 *   <li>Client: {@code SSL_CTX} with {@code SSL_VERIFY_NONE} (loopback only — no CA chain).</li>
 *   <li>Transport: {@link ServerSocketChannel}/{@link SocketChannel} loopback pair — raw
 *       POSIX FD extracted via {@code sun.nio.ch.SocketChannelImpl} reflection (test scope only,
 *       never used on hot path).</li>
 *   <li>Handshake: driven by {@link OffHeapTlsEngine#beginHandshake(LoanedBuffer)} loop.</li>
 *   <li>Data: 512 bytes of {@code 0xAB} encrypted by server, decrypted by client.</li>
 * </ul>
 *
 * <h2>Platform</h2>
 * <p>Linux only — {@code SSL_set_fd} requires POSIX file descriptors.
 * Disabled on Windows ({@code SSL_set_fd} is unavailable for Winsock SOCKETs via FFM).
 *
 * <h2>OpenSSL availability</h2>
 * <p>Skipped via {@link org.junit.jupiter.api.Assumptions#assumeTrue} if OpenSSL is not
 * found on the path. CI pipelines targeting TRL-4 MUST have OpenSSL 3.x installed.
 *
 * @since 0.5.0
 */
@Tag("integration")
@EnabledOnOs(OS.LINUX)
@DisplayName("IT: OffHeapTlsEngine — TLS 1.3 loopback handshake + round-trip")
class OffHeapTlsEngineLoopbackIT {

    // =========================================================================
    // One-time bootstrap — shared across all @Test methods
    // =========================================================================

    private static CoreSslHandles handles;

    /**
     * Community-tier handle for {@code SSL_set_fd(SSL*, int)} — resolved separately
     * from {@link CoreSslHandles} because Core is BIO-agnostic.
     *
     * <p>In production Community code, this handle would live in a
     * {@code CommunityTlsHandles} carrier. Here it is resolved inline to
     * simulate the Community tier's "attach fd-owner BIO, then notifyBound()" pattern.
     */
    private static java.lang.invoke.MethodHandle sslSetFdHandle;

    @BeforeAll
    static void loadOpenSsl() {
        try {
            handles = CoreOpenSslLoader.load(Arena.global());
            // Resolve SSL_set_fd separately — Community-tier concern only
            java.lang.foreign.Linker linker = java.lang.foreign.Linker.nativeLinker();
            java.lang.foreign.SymbolLookup lookup = java.lang.foreign.SymbolLookup.loaderLookup()
                    .or(java.lang.foreign.SymbolLookup.libraryLookup("libssl.so.3", Arena.global()));
            sslSetFdHandle = linker.downcallHandle(
                    lookup.find("SSL_set_fd").orElseThrow(),
                    java.lang.foreign.FunctionDescriptor.of(
                            java.lang.foreign.ValueLayout.JAVA_INT,
                            java.lang.foreign.ValueLayout.JAVA_LONG,
                            java.lang.foreign.ValueLayout.JAVA_INT));
        } catch (Exception e) {
            assumeTrue(false, "OpenSSL not available — skipping loopback IT: " + e.getMessage());
        }
    }

    /**
     * Simulates Community-tier BIO wiring: calls {@code SSL_set_fd(sslPtr, fd)}
     * via the Community-owned handle, then signals the Core engine that the BIO
     * is ready via {@link OffHeapTlsEngine#notifyBound()}.
     *
     * <p>This is the exact pattern a {@code CommunityTlsEngine} would use —
     * {@link OffHeapTlsEngine} has zero knowledge of the fd or {@code SSL_set_fd}.
     */
    private static void communityBind(OffHeapTlsEngine engine, int fd) {
        long sslPtr = engine.sslPointerForDiagnostics();
        try {
            int result = (int) sslSetFdHandle.invokeExact(sslPtr, fd);
            assumeTrue(result == 1, "SSL_set_fd failed (result=" + result + ")");
        } catch (Throwable t) {
            throw new org.opentest4j.TestAbortedException("SSL_set_fd threw: " + t.getMessage());
        }
        engine.notifyBound();
    }

    // =========================================================================
    // Shared stub allocator (test scope — not production hot path)
    // =========================================================================

    private static final Arena ALLOC_ARENA = Arena.ofShared(); //NOPMD DirectArena — test harness only

    private static final MemoryAllocator ALLOC = new MemoryAllocator() {
        @Override
        public LoanedBuffer allocate(AllocationHint hint) {
            return ArenaLoanedBuffer.allocate(ALLOC_ARENA, hint, 16_384);
        }
        @Override public LoanedBuffer allocateNetwork(int b)         { return allocate(AllocationHint.MEDIUM); }
        @Override public LoanedBuffer allocateCarrierSlab(int i)     { return allocate(AllocationHint.MEDIUM); }
        @Override public LoanedBuffer allocateInfrastructure(long b) { return allocate(AllocationHint.MEDIUM); }
        @Override public MemoryStats  stats()                        { return MemoryStats.zero(); }
        @Override public void         close()                        { ALLOC_ARENA.close(); }
    };

    @AfterAll
    static void closeAllocArena() {
        ALLOC_ARENA.close();
    }

    // =========================================================================
    // Self-signed certificate generation helpers
    // =========================================================================

    /**
     * Resolved absolute path to the {@code openssl} binary, or {@code null} if not found.
     * Prefers {@code /usr/bin/openssl} (standard Linux location), then searches {@code PATH}.
     */
    private static final String OPENSSL_CMD = resolveOpenSslCmd();

    private static String resolveOpenSslCmd() {
        java.nio.file.Path fixed = java.nio.file.Paths.get("/usr/bin/openssl");
        if (java.nio.file.Files.isExecutable(fixed)) {
            return fixed.toString();
        }
        String path = System.getenv("PATH");
        if (path != null) {
            for (String dir : path.split(java.io.File.pathSeparator)) {
                java.nio.file.Path candidate = java.nio.file.Paths.get(dir, "openssl");
                if (java.nio.file.Files.isExecutable(candidate)) {
                    return candidate.toString();
                }
            }
        }
        return null;
    }

    /**
     * Generates a self-signed certificate and private key using the {@code openssl} CLI.
     * Returns {@code null} if the {@code openssl} binary is not available.
     */
    private static CertPair generateSelfSignedCert(Path dir) throws Exception {
        if (OPENSSL_CMD == null) {
            return null;
        }
        Path certFile = dir.resolve("server.crt");
        Path keyFile  = dir.resolve("server.key");

        ProcessBuilder pb = new ProcessBuilder(
                OPENSSL_CMD, "req", "-x509", "-newkey", "rsa:2048",
                "-keyout", keyFile.toString(),
                "-out", certFile.toString(),
                "-days", "1",
                "-nodes",
                "-subj", "/CN=localhost"
        );
        pb.redirectOutput(ProcessBuilder.Redirect.DISCARD);
        pb.redirectError(ProcessBuilder.Redirect.DISCARD);
        try (ManagedProcess proc = new ManagedProcess(pb.start())) {
            int exitCode = proc.waitFor();
            if (exitCode != 0) {
                return null;
            }
        }
        return new CertPair(certFile.toString(), keyFile.toString());
    }

    private record CertPair(String certPath, String keyPath) {}

    /**
     * {@link AutoCloseable} wrapper for {@link Process} that enforces
     * {@link Process#destroyForcibly()} on {@link #close()}, guaranteeing the OS
     * process is reaped even if {@link Process#waitFor()} throws or is not called
     * in all execution paths. Using this adapter makes the explicit teardown intent
     * visible to static analysis tools (e.g. SonarQube S2093).
     */
    private record ManagedProcess(Process process) implements AutoCloseable {
        int waitFor() throws InterruptedException {
            return process.waitFor();
        }

        @Override
        public void close() {
            process.destroyForcibly();
        }
    }

    /**
     * {@link AutoCloseable} wrapper for a native {@code SSL_CTX*} pointer.
     * Calls {@code SSL_CTX_free} on {@link #close()} to ensure the context is freed
     * even if the enclosing test throws, satisfying SonarQube S2095.
     */
    private record SslCtxHandle(CoreSslHandles handles, long ptr) implements AutoCloseable {
        @Override
        public void close() {
            handles.ctx().invokeCtxFree(ptr);
        }
    }

    // =========================================================================
    // POSIX FD extraction from NIO SocketChannel (test harness only)
    // =========================================================================

    /**
     * Extracts the native POSIX file descriptor integer from a {@link SocketChannel}
     * using internal JDK reflection. Restricted to the test harness — production code
     * MUST NEVER call this method.
     */
    private static int extractFd(SocketChannel ch) throws Exception {
        java.lang.reflect.Method getFdVal = ch.getClass().getDeclaredMethod("getFDVal");
        getFdVal.setAccessible(true); //NOPMD AvoidAccessibilityAlteration — test harness only
        return (int) getFdVal.invoke(ch);
    }

    // =========================================================================
    // SSL_CTX construction helpers
    // =========================================================================

    private SslCtxHandle buildServerCtx(String certPath, String keyPath) {
        long methodPtr = handles.ctx().invokeServerMethod();
        long ctxPtr    = handles.ctx().invokeCtxNew(methodPtr);
        assumeTrue(ctxPtr != 0L, "SSL_CTX_new returned NULL — OpenSSL init failed");

        SslCtxHandle ctx = new SslCtxHandle(handles, ctxPtr);
        try (Arena arena = Arena.ofConfined()) { //NOPMD DirectArena — cert path strings only, not session memory
            MemorySegment certSeg = arena.allocateFrom(certPath);
            MemorySegment keySeg  = arena.allocateFrom(keyPath);

            int certResult = handles.ctx().invokeCtxUseCertFile(
                    ctxPtr, certSeg.address(), CoreOpenSslLoader.SSL_FILETYPE_PEM);
            if (certResult != 1) {
                ctx.close();
                throw new org.opentest4j.TestAbortedException(
                        "SSL_CTX_use_certificate_file failed (result=" + certResult + ")");
            }

            int keyResult = handles.ctx().invokeCtxUseKeyFile(
                    ctxPtr, keySeg.address(), CoreOpenSslLoader.SSL_FILETYPE_PEM);
            if (keyResult != 1) {
                ctx.close();
                throw new org.opentest4j.TestAbortedException(
                        "SSL_CTX_use_PrivateKey_file failed (result=" + keyResult + ")");
            }

            int checkResult = handles.ctx().invokeCtxCheckKey(ctxPtr);
            if (checkResult != 1) {
                ctx.close();
                throw new org.opentest4j.TestAbortedException("SSL_CTX_check_private_key mismatch");
            }
        }
        handles.ctx().invokeCtxSetVerify(ctxPtr, CoreOpenSslLoader.SSL_VERIFY_NONE);
        return ctx;
    }

    private SslCtxHandle buildClientCtx() {
        long methodPtr = handles.ctx().invokeClientMethod();
        long ctxPtr    = handles.ctx().invokeCtxNew(methodPtr);
        assumeTrue(ctxPtr != 0L, "SSL_CTX_new (client) returned NULL");
        handles.ctx().invokeCtxSetVerify(ctxPtr, CoreOpenSslLoader.SSL_VERIFY_NONE);
        return new SslCtxHandle(handles, ctxPtr);
    }

    // =========================================================================
    // Test: TLS 1.3 handshake completes over a loopback TCP socket pair
    // =========================================================================

    @Test
    @DisplayName("TLS 1.3 handshake completes over real loopback TCP — both engines reach ACTIVE")
    void tlsHandshakeCompletesOverLoopback(@TempDir Path tempDir) throws Exception {
        CertPair cert = generateSelfSignedCert(tempDir);
        assumeTrue(cert != null, "openssl CLI not available — skipping loopback IT");

        try (SslCtxHandle serverCtx = buildServerCtx(cert.certPath(), cert.keyPath());
             SslCtxHandle clientCtx = buildClientCtx();
             ServerSocketChannel serverSock = ServerSocketChannel.open();
             SocketChannel clientSock       = SocketChannel.open()) {

            serverSock.configureBlocking(true);
            serverSock.bind(new InetSocketAddress("127.0.0.1", 0));
            int port = ((InetSocketAddress) serverSock.getLocalAddress()).getPort();

            clientSock.configureBlocking(true);
            clientSock.connect(new InetSocketAddress("127.0.0.1", port));

            try (SocketChannel acceptedSock = serverSock.accept()) {
                int serverFd = extractFd(acceptedSock);
                int clientFd = extractFd(clientSock);

                assumeTrue(serverFd > 0 && clientFd > 0,
                        "Could not extract socket FDs via getFDVal — skipping loopback IT");

                try (OffHeapTlsEngine serverEngine = new OffHeapTlsEngine(handles, serverCtx.ptr(), true, ALLOC);
                     OffHeapTlsEngine clientEngine = new OffHeapTlsEngine(handles, clientCtx.ptr(), false, ALLOC);
                     LoanedBuffer serverOut = ALLOC.allocate(AllocationHint.MEDIUM);
                     LoanedBuffer clientOut = ALLOC.allocate(AllocationHint.MEDIUM)) {

                    ScopedValue.where(KernelProviders.MEMORY_ALLOCATOR, ALLOC).run(() -> {
                        communityBind(serverEngine, serverFd);
                        communityBind(clientEngine, clientFd);

                        driveHandshake(serverEngine, serverOut, clientEngine, clientOut);

                        assertThat(serverEngine.phase())
                                .as("Server engine must reach ACTIVE after handshake")
                                .isEqualTo(TlsPhase.ACTIVE);
                        assertThat(clientEngine.phase())
                                .as("Client engine must reach ACTIVE after handshake")
                                .isEqualTo(TlsPhase.ACTIVE);
                        assertThat(serverEngine.isHandshakeComplete()).isTrue();
                        assertThat(clientEngine.isHandshakeComplete()).isTrue();
                        assertThat(serverEngine.negotiatedProtocol())
                                .as("No ALPN configured — negotiatedProtocol() must be null")
                                .isNull();
                    });
                }
            }
        }
    }

    // =========================================================================
    // Test: TLS 1.3 round-trip data transfer (wrap → unwrap)
    // =========================================================================

    @Test
    @DisplayName("TLS 1.3 round-trip: server encrypts 512 bytes, client decrypts — data matches")
    void tlsRoundTripDataTransfer(@TempDir Path tempDir) throws Exception {
        CertPair cert = generateSelfSignedCert(tempDir);
        assumeTrue(cert != null, "openssl CLI not available — skipping loopback IT");

        final int payloadSize = 512;

        try (SslCtxHandle serverCtx = buildServerCtx(cert.certPath(), cert.keyPath());
             SslCtxHandle clientCtx = buildClientCtx();
             ServerSocketChannel serverSock = ServerSocketChannel.open();
             SocketChannel clientSock       = SocketChannel.open()) {

            serverSock.configureBlocking(true);
            serverSock.bind(new InetSocketAddress("127.0.0.1", 0));
            int port = ((InetSocketAddress) serverSock.getLocalAddress()).getPort();

            clientSock.configureBlocking(true);
            clientSock.connect(new InetSocketAddress("127.0.0.1", port));

            try (SocketChannel acceptedSock = serverSock.accept()) {
                int serverFd = extractFd(acceptedSock);
                int clientFd = extractFd(clientSock);

                assumeTrue(serverFd > 0 && clientFd > 0,
                        "Could not extract socket FDs — skipping loopback IT");

                try (OffHeapTlsEngine serverEngine = new OffHeapTlsEngine(handles, serverCtx.ptr(), true, ALLOC);
                     OffHeapTlsEngine clientEngine = new OffHeapTlsEngine(handles, clientCtx.ptr(), false, ALLOC);
                     LoanedBuffer serverOut   = ALLOC.allocate(AllocationHint.MEDIUM);
                     LoanedBuffer clientOut   = ALLOC.allocate(AllocationHint.MEDIUM);
                     LoanedBuffer plaintext   = ALLOC.allocate(AllocationHint.MEDIUM);
                     LoanedBuffer decrypted   = ALLOC.allocate(AllocationHint.MEDIUM)) {

                    ScopedValue.where(KernelProviders.MEMORY_ALLOCATOR, ALLOC).run(() -> {
                        communityBind(serverEngine, serverFd);
                        communityBind(clientEngine, clientFd);
                        driveHandshake(serverEngine, serverOut, clientEngine, clientOut);

                        plaintext.segment().asSlice(0, payloadSize).fill((byte) 0xAB);
                        plaintext.setSize(payloadSize);

                        TlsStatus wrapStatus = serverEngine.wrap(plaintext, serverOut);
                        assertThat(wrapStatus)
                                .as("Server wrap() must succeed")
                                .isEqualTo(TlsStatus.OK);

                        TlsStatus unwrapStatus = clientEngine.unwrap(clientOut, decrypted);
                        assertThat(unwrapStatus)
                                .as("Client unwrap() must succeed")
                                .isEqualTo(TlsStatus.OK);
                        assertThat(decrypted.size())
                                .as("Decrypted byte count must equal original payload")
                                .isEqualTo(payloadSize);

                        MemorySegment actual = decrypted.segment().asSlice(0, decrypted.size());
                        try (LoanedBuffer patternBuf = ALLOC.allocate(AllocationHint.MEDIUM)) {
                            patternBuf.segment().asSlice(0, decrypted.size()).fill((byte) 0xAB);
                            MemorySegment pattern = patternBuf.segment().asSlice(0, decrypted.size());
                            assertThat(actual.mismatch(pattern))
                                    .as("All decrypted bytes must equal 0xAB — mismatch offset (−1 = none)")
                                    .isEqualTo(-1L);
                        }
                    });
                }
            }
        }
    }

    // =========================================================================
    // Test: TLS session memory is tracked by WatermarkManager (SESSION alloc hint)
    // =========================================================================

    @Test
    @DisplayName("SESSION-slab allocated via MemoryAllocator — WatermarkManager backpressure path visible")
    void sessionSlabAllocatedViaMemoryAllocator(@TempDir Path tempDir) throws Exception {
        CertPair cert = generateSelfSignedCert(tempDir);
        assumeTrue(cert != null, "openssl CLI not available — skipping loopback IT");

        final boolean[] sessionAllocCalled = {false};

        try (SslCtxHandle ctx            = buildServerCtx(cert.certPath(), cert.keyPath());
             Arena trackArena            = Arena.ofShared(); //CHECKSTYLE:OFF — test harness
             MemoryAllocator tracking    = buildTrackingAllocator(trackArena, sessionAllocCalled);
             OffHeapTlsEngine engine     = new OffHeapTlsEngine(handles, ctx.ptr(), true, tracking)) {
            assertThat(engine.sslPointerForDiagnostics())
                    .as("SSL* pointer must be non-zero after construction")
                    .isNotZero();
        }

        assertThat(sessionAllocCalled[0])
                .as("NativeCipherContext MUST call allocator.allocate(AllocationHint.SESSION) " +
                    "so that WatermarkManager can track TLS session memory and apply EX-MEM-1001 backpressure")
                .isTrue();
    }

    private static MemoryAllocator buildTrackingAllocator(Arena trackArena,
                                                          boolean[] sessionAllocCalled) {
        return new MemoryAllocator() {
            @Override
            public LoanedBuffer allocate(AllocationHint hint) {
                if (hint == AllocationHint.SESSION) {
                    sessionAllocCalled[0] = true;
                }
                return ArenaLoanedBuffer.allocate(trackArena, hint, 16_384);
            }
            @Override public LoanedBuffer allocateNetwork(int b)         { return allocate(AllocationHint.MEDIUM); }
            @Override public LoanedBuffer allocateCarrierSlab(int i)     { return allocate(AllocationHint.MEDIUM); }
            @Override public LoanedBuffer allocateInfrastructure(long b) { return allocate(AllocationHint.MEDIUM); }
            @Override public MemoryStats  stats()                        { return MemoryStats.zero(); }
            @Override public void         close()                        { /* test harness — trackArena closed by outer try-with-resources */ }
        };
    }

    // =========================================================================
    // Handshake driver — interleaves server/client steps until both reach ACTIVE
    // =========================================================================

    /**
     * Drives the TLS handshake by alternating {@link OffHeapTlsEngine#beginHandshake}
     * calls between server and client until both engines reach {@link TlsPhase#ACTIVE}
     * or a maximum step limit is exceeded (guard against infinite loops in test failure paths).
     */
    private static void driveHandshake(OffHeapTlsEngine server, LoanedBuffer serverBuf,
                                       OffHeapTlsEngine client, LoanedBuffer clientBuf) {
        final int maxSteps = 64;
        int steps = 0;

        while ((server.phase() != TlsPhase.ACTIVE || client.phase() != TlsPhase.ACTIVE)
                && steps++ < maxSteps) {
            if (server.phase() != TlsPhase.ACTIVE) {
                server.beginHandshake(serverBuf);
            }
            if (client.phase() != TlsPhase.ACTIVE) {
                client.beginHandshake(clientBuf);
            }
        }

        assertThat(server.phase() == TlsPhase.ACTIVE && client.phase() == TlsPhase.ACTIVE)
                .as("TLS handshake did not complete within %d steps — server=%s, client=%s",
                    maxSteps, server.phase(), client.phase())
                .isTrue();
    }
}
